<a href="https://colab.research.google.com/github/N280D/Data-MachineLearning/blob/main/MachineLearning__titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
import pandas as pd


from google.colab import drive
drive.mount('/content/drive')
df=pd.read_csv('/content/drive/MyDrive/titanic.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [88]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score
from imblearn.over_sampling import RandomOverSampler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer


In [89]:
df=df.drop(["Name", "PassengerId","Cabin"],axis=1)

In [90]:
df=df.drop(['Ticket'],axis=1)



In [91]:

feats=df.drop('Survived',axis=1)

target=df['Survived']



In [92]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [93]:
X_train,X_test,y_train,y_test=train_test_split(feats,target,test_size=0.2,random_state=42)


In [94]:
X_train.head()


cat_train=X_train[['Sex','Embarked']]

num_train=X_train[['Pclass','Age' ,'SibSp','Parch', 'Fare']]


cat_test=X_test[['Sex','Embarked']]

num_test=X_test[['Pclass','Age' ,'SibSp','Parch', 'Fare']]


In [28]:
cat_train.head()

Sex Embarked
331    male        S
733    male        S
382    male        S
704    male        S
813  female        S

In [95]:
from sklearn.impute import SimpleImputer

imp=SimpleImputer(missing_values=np.nan,strategy='median')

imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

num_train=imp.fit_transform(num_train)

num_test=imp.transform(num_test)

cat_train=imputer.fit_transform(cat_train)

cat_test=imputer.transform(cat_test)


In [86]:
df.keys()
num_test
num_train

array([], shape=(712, 0), dtype=float64)

In [97]:
ohe=OneHotEncoder(drop='first',sparse=False)
cat_train=ohe.fit_transform(cat_train)

cat_test=ohe.transform(cat_test)
cat_train

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       ...,
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.]])

In [43]:
cat_train_tips=pd.get_dummies(df)
cat_train_tips
cat_train_tips.keys()

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female',
       'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [99]:
cat_train



array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       ...,
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.]])

In [100]:
X_test=np.concatenate([num_test,cat_test], axis =1)

In [101]:
X_train= np.concatenate([num_train,cat_train], axis =1)


In [102]:
X_train

array([[ 1. , 45.5,  0. , ...,  1. ,  0. ,  1. ],
       [ 2. , 23. ,  0. , ...,  1. ,  0. ,  1. ],
       [ 3. , 32. ,  0. , ...,  1. ,  0. ,  1. ],
       ...,
       [ 3. , 41. ,  2. , ...,  1. ,  0. ,  1. ],
       [ 1. , 14. ,  1. , ...,  0. ,  0. ,  1. ],
       [ 1. , 21. ,  0. , ...,  1. ,  0. ,  1. ]])

In [103]:
from sklearn.linear_model import LogisticRegression
reglog=LogisticRegression()

reglog.fit(X_train,y_train)

print('Score sur ensemble train :' ,reglog.score(X_train,y_train))

print('Score sur ensemble test :' ,reglog.score(X_test,y_test))


Score sur ensemble train : 0.8019662921348315
Score sur ensemble test : 0.7988826815642458


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
